name: 'PR Custom Review'
description: 'An action to enforce complex pull request approval cases'
author: 'sergejparity'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  config-file:
    required: false
    description: 'Path to the config file'
    default: './.github/pr-custom-review.yml'
  token:
    required: true
    description: 'Repository token'
runs:
  using: 'node12'
  main: 'dist/index.js'
